name: Build and Upload Qt6 App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Qt6 and build tools
      run: |
        sudo apt update
        sudo apt install -y qt6-base-dev qt6-base-dev-tools qt6-qmake qt6-tools-dev qt6-tools-dev-tools qt6-multimedia-dev libgl-dev libopengl-dev mesa-common-dev

    - name: Configure project
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build project
      run: |
        cd build && make

    - name: Download linuxdeploy and Qt plugin
      run: |
        mkdir appimage-tools
        cd appimage-tools
        wget -c https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        wget -c https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
        chmod +x linuxdeploy*.AppImage

    - name: Bundle into AppImage with Qt
      run: |
        ./appimage-tools/linuxdeploy-x86_64.AppImage \
          --appdir AppDir \
          --executable ./build/jeopardy \
          --desktop-file jeopardy.desktop \
          --icon-file jeopardy.png \
          --plugin qt \
          -o appimage

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: Jeopardy-AppImage
        path: ./*.AppImage

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: jeopardy-binary
        path: ./build/jeopardy
