name: Build and Upload Qt5 App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Qt5 and build tools
      run: |
        sudo apt update
        sudo apt install -y qt5-qmake qtbase5-dev qtbase5-dev-tools qtmultimedia5-dev qtxmlpatterns5-dev-tools libphonon4qt5-dev build-essential

    - name: Configure project
      run: |
        qmake

    - name: Build project
      run: |
        make

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: jeopardy-binary
        path: ./jeopardy
